LocalAtBrown/article-rec-training-job

Karfile, README.md
this adds helper to make dev deploys easier. now that we have a dev stack for each partner, it's tedious to deploy each stack individually without something like this 
✅ `kar deploy` command works as expected
=> Improve dev deploys

cdk/lib/app-stack.ts, cdk/lib/partners.ts, env.json, job/steps/warehouse.py, sites/philadelphia_inquirer.py, sites/site.py, sites/texas_tribune.py, sites/washington_city_paper.py
add a 2-year article age threshold for philly inquirer article recommendations 
do a few extra things to get the dev job running for pi:
- double memory allocation for pi
- run dev job at same frequency as prod 
✅  seeing fewer recs for washington city paper (will test philly inquirer in dev) 
compare branch
```
INFO:root:Created model with id 3805
INFO:root:Writing 17640 recommendations...
```
to main
```
INFO:root:Created model with id 3803
INFO:root:Writing 26070 recommendations...
```
✅ pi job runs to completion on dev and saves the expected num of recs (~300k)
=> Max article age by site

cdk/lib/partners.ts
re-order schedule so shorter job (texas tribune) goes first and the inquirer gets more room to run on its own
deployed to dev, prod diff looks as expected 
```
~/lnl/article-rec-training-job/cdk [reorder-schedule] npx cdk diff PhiladelphiaInquirerArticleRecTrainingJob 
Including dependency stacks: ArticleRecTrainingJobCentralResourcesStack
Stack ArticleRecTrainingJobCentralResourcesStack
There were no differences
Stack PhiladelphiaInquirerArticleRecTrainingJob
Resources
[~] AWS::ECS::TaskDefinition PhiladelphiaInquirerArticleRecTrainingJobTaskDefinition PhiladelphiaInquirerArticleRecTrainingJobTaskDefinition7D26D8FF replace
└─ [~] ContainerDefinitions (requires replacement)
└─ @@ -24,7 +24,7 @@
[ ]       {
[ ]         "Ref": "AWS::URLSuffix"
[ ]       },
[-] …
```
=> [change] reorder schedule

job/steps/scrape_metadata.py, sites/philadelphia_inquirer.py, sites/texas_tribune.py, sites/washington_city_paper.py
- Added a message to when `ArticleScrapingError` is thrown in several places
- Made warnings logged by `scrape_metadata.py` show the type of ArticleScrapingError being raised in addition to the path and message
Both of these changes should make it easier to detect potential scraping problems when looking at CloudWatch logs
=> [change] improve metadata scraping warnings

job/steps/warehouse.py
add the TRUNCATECOLUMNS option to the redshift copy command so that any paths that are somehow too long don't break the copy. This is a rough fix that makes sure we don't hit the "data too long" issue, and pushes the issue to the code that will ignore it as a valid URL further along in the pipeline. It will not be included in the model.
Ran changes locally with the site that caused the issue in the first place, and it did not error. It also logged the invalid path where we expected.
=> add truncatecolumns option to redshift copy

.gitignore, .vscode/settings.json, sites/helpers.py, sites/philadelphia_inquirer.py, sites/texas_tribune.py, sites/washington_city_paper.py, tests/sites/test_helpers.py
One insight from #136 is that it would be great to catch HTTP errors before actually looking at the response HTML. This PR adds an extra layer of validation, which inspects the response code, to the process of fetching articles from our partner news sites. It also consolidates the different ways we validate responses from different publications into one customizable `validate_response()` pipeline. 
All tests passed locally, although I'm yet to add unit tests for the added functions.
=> [add] http error handling

db/helpers.py, job/steps/save_defaults.py, job/steps/save_predictions.py
Update the save_predictions function to accept a model_type argument and set the default case to `ModelType.ARTICLE` so as to maintain current behavior. Makes a few changes to some DB helper functions as well to make proper use of the `ModelType` enumeration. This allows us to use this same function in the future to save recommendations generated by different types of models.
=> Update save predictions

job/steps/collaborative_filtering/fetch_data.py, sites/philadelphia_inquirer.py, sites/singleton.py, sites/site.py, sites/texas_tribune.py, sites/washington_city_paper.py, tests/sites/test_philadelphia_inquirer.py, tests/test_fetch_data.py
This PR updates the Site object. It was previously a named tuple. `Site` is now an abstract base class, a data class, and a singleton. This means that when a class uses it as its metaclass, the following happens:
- There can only be one instantiation of the class (singleton pattern)
- It expects certain functions to be implemented (abstract base class)
- It expects certain properties to be passed in (data class)
The reason we are doing this is to enforce stricter structure and typing on this central configuration object. It is a common pattern across each partner site, and by adding all this strictness we reduce the probability of bugs. (For example, the named tuple approach would allow someone to define the "extract_external_id" field as a literal integer. That would break the program. …
=> Update site object

job/job.py
Now that the `IndexError` fix (see #143) is working well, as shown [in the logs](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/ArticleRecTrainingJobLogGroup/log-events$3FfilterPattern$3D$2522batch+size+of$2522$26start$3D-2419200000), we can remove the code that helped diagnose the error (see #140).
All tests passed.
=> Remove code to copy IndexError data to S3

job/job.py, job/steps/collaborative_filtering/fetch_data.py, job/steps/collaborative_filtering/scrape_metadata.py, job/steps/collaborative_filtering/warehouse.py, sites/config.py, sites/philadelphia_inquirer.py, sites/site.py, sites/strategy.py, sites/texas_tribune.py, sites/washington_city_paper.py
This PR attempts to minimally change the current `Site` object so that it works with different recommendation approaches/strategies (CF, SS, CF-SS hybrid, or something else). There are two main changes:
- `Site` properties that currently are config variables for the CF model (`fields`, `training_params`, `scrape_config`, `max_article_age`) and for the default popularity model (`popularity_window`) are moved to the models' respective config dataclasses. These dataclasses are defined in `sites/config.py`. A new property `Site.config` is added, which itself is a dataclass housing all the different config dataclasses a site requires.
- Toward the ability to toggle between different recommendation strategies, two new `Site` properties are added, `Site.strategy` and `Site.strategy_fallback`. …
=> SS: Change Site object to accommodate different rec approaches

job/steps/scrape_metadata.py, sites/washington_city_paper.py, tests/test_scrape_metadata.py
Recently, a slew of [Postgres errors](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/ArticleRecTrainingJobLogGroup/log-events/TexasTribuneArticleRecTrainingJob$252FTexasTribuneArticleRecTrainingJobTaskContainer$252Fb5343b2c8f0140d5916c71b2c81e46c4) happened because the job prematurely deleted a Texas Tribune article from the `article` table upon encountering a 404 error while trying to rescrape and update it.
This PR restricts this deletion logic to sponsored (excluded) articles from the Washington City Paper, as separating original and sponsored WCP content was the only motivation toward deletion (see #55).
A single test inside `tests/test_scraped_metadata.py` was modified to accommodate this change. All tests passed.
=> Remove deletion upon error in article database update for TT and PI

db/helpers.py, db/mappings/model.py, job/strategies/collaborative_filtering.py, job/strategies/popularity.py, job/strategies/semantic_similarity.py, job/strategies/templates/strategy.py
This PR translates the existing code for collaborative filtering into the new class hierarchy that we created. In addition to that, it makes adjustments in subclass `SemanticSimilarity` to make it compatible with `Strategy` and `CollaborativeFiltering`. Finally, it also fleshes out the routines for `Popularity`.
None of the previous routines for collaborative filtering has been changed. They are called from inside the new code.
Only two files outside the `Strategy` hierarchy have been tweaked:
- [`db/helpers.py`](https://github.com/LocalAtBrown/article-rec-training-job/blob/refactor-collaborative-filtering/db/helpers.py): to prevent a circular import
- [`db/mappings/model.py`](https://github.com/LocalAtBrown/article-rec-training-job/blob/refactor-collaborative-filtering/db/mappings/model.p …
=> refactor CollaborativeFiltering and SemanticSimilarity as subclasses of Strategy

sites/philadelphia_inquirer.py
Simple fix for the empty DataFrame returned by `warehouse.get_default_recs` at the 00:00 UTC mark.
=> Incrase PI popularity window to 2 days

sites/texas_tribune.py
There was a problem with the Snowplow collection pipeline that made Texas Tribune events unable to flow into enriched S3 buckets since May 27 (7 days ago), throwing off the default-recs calculation. Temporarily increases Texas Tribune popularity window to 14 days to ward off CloudWatch errors until we can fix this problem.
=> Increase TT default popularity window to 14 days

sites/texas_tribune.py
Now that TT jobs are running fine again, change its popularity window back to 7 days.
=> Change TT popularity window back to 7 days

sites/texas_tribune.py
Temporarily incrase TT popularity window to 14 days to stop new training job errors from spawning. Will revert once we get those fixed.
=> Increase TT popularity window

cdk/lib/app-stack.ts, cdk/lib/helpers.ts, cdk/lib/partners.ts, cdk/package-lock.json
Temporarily reduce WCP job runs to once a day, at 6 AM UTC, until WCP is ready to resume usual schedule.
```bash
❯ cdk1 diff WashingtonCityPaperArticleRecTrainingJob
Including dependency stacks: ArticleRecTrainingJobCentralResourcesStack
Stack ArticleRecTrainingJobCentralResourcesStack
There were no differences
Stack WashingtonCityPaperArticleRecTrainingJob
Resources
[~] AWS::ECS::TaskDefinition WashingtonCityPaperArticleRecTrainingJobTaskDefinition WashingtonCityPaperArticleRecTrainingJobTaskDefinitionECBC0787 replace
└─ [~] ContainerDefinitions (requires replacement)
└─ @@ -24,7 +24,7 @@
[ ]       {
[ ]         "Ref": "AWS::URLSuffix"
[ ]       },
[-]       "/aws-cdk/assets:4d3c19e2698d4ba227e54c029d176200174d974c369d6b299f6c942b0e5ac69e"
[+] …
```
=> Limit WCP cron to once a day

env.json, job/job.py, job/steps/scrape_metadata.py, sites/philadelphia_inquirer.py, sites/site.py, sites/texas_tribune.py, sites/washington_city_paper.py
Increases `HOURS_OF_DATA` for WCP from 2 hours to 24 hours to reflect the once-a-day schedule change (see #179). To accommodate this, move `HOURS_OF_DATA` from global config to site config.
All tests passed.
=> Increase WCP's window to fetch raw events

app.py, article_rec_training_job/components/page_writers/postgres.py, configs/example.yaml, tests/integration/components/page_writers/test_postgres.py, tests/unit/config-example.yaml, tests/unit/test_app.py
- Adds an option to have the Postgres page writer bypass the timestamp-based `on_conflict_do_update` where-condition. It's useful when backfilling articles right after a database schema change.
- Adds a new test for this option.
=> Add option to force-update in Postgres page writer

scripts/backfill_task.py
While moving `HOURS_OF_DATA` from global config to site config (see #180), we forgot to update the backfill task to reflect this change. This PR fixes this problem.
Ideally, there should be a test for this, though it's not a priority given how rare we run the backfill script. The backfill functionality of the (currently developed, see the `dev` branch of this repo) GA4-backed training job will be thoroughly tested, however.
=> Re-allow backfill task to go through full 24 hours
